export const PHONICS_AUDIO_MAP = {
  "/i:/": { audioFile: "/phonics-audio/i-long.ogg", enabled: true },
  "/ɪ/": { audioFile: "/phonics-audio/i-short.ogg", enabled: true },
  "/e/": { audioFile: "/phonics-audio/e.ogg", enabled: true },
  "/æ/": { audioFile: "/phonics-audio/ae.ogg", enabled: true },
  "/ɑ:/": { audioFile: "/phonics-audio/a-long.ogg", enabled: true },
  "/ɒ/": { audioFile: "/phonics-audio/o-short.ogg", enabled: true },
  "/ɔ:/": { audioFile: "/phonics-audio/or-long.ogg", enabled: true },
  "/ʊ/": { audioFile: "/phonics-audio/u-short.ogg", enabled: true },
  "/u:/": { audioFile: "/phonics-audio/u-long.ogg", enabled: true },
  "/ʌ/": { audioFile: "/phonics-audio/uh.ogg", enabled: true },
  "/ɜ:/": { audioFile: "/phonics-audio/er-long.ogg", enabled: true },
  "/ə/": { audioFile: "/phonics-audio/schwa.ogg", enabled: true },
  "/eɪ/": { enabled: false },
  "/aɪ/": { enabled: false },
  "/ɔɪ/": { enabled: false },
  "/əʊ/": { enabled: false },
  "/aʊ/": { enabled: false },
  "/ɪə/": { enabled: false },
  "/eə/": { enabled: false },
  "/ʊə/": { enabled: false },
  "/p/": { audioFile: "/phonics-audio/p.ogg", enabled: true },
  "/b/": { audioFile: "/phonics-audio/b.ogg", enabled: true },
  "/t/": { audioFile: "/phonics-audio/t.ogg", enabled: true },
  "/d/": { audioFile: "/phonics-audio/d.ogg", enabled: true },
  "/k/": { audioFile: "/phonics-audio/k.ogg", enabled: true },
  "/g/": { audioFile: "/phonics-audio/g.ogg", enabled: true },
  "/f/": { audioFile: "/phonics-audio/f.ogg", enabled: true },
  "/v/": { audioFile: "/phonics-audio/v.ogg", enabled: true },
  "/θ/": { audioFile: "/phonics-audio/theta.ogg", enabled: true },
  "/ð/": { audioFile: "/phonics-audio/eth.ogg", enabled: true },
  "/s/": { audioFile: "/phonics-audio/s.ogg", enabled: true },
  "/z/": { audioFile: "/phonics-audio/z.ogg", enabled: true },
  "/ʃ/": { audioFile: "/phonics-audio/esh.ogg", enabled: true },
  "/ʒ/": { audioFile: "/phonics-audio/ezh.ogg", enabled: true },
  "/h/": { audioFile: "/phonics-audio/h.ogg", enabled: true },
  "/m/": { audioFile: "/phonics-audio/m.ogg", enabled: true },
  "/n/": { audioFile: "/phonics-audio/n.ogg", enabled: true },
  "/ŋ/": { audioFile: "/phonics-audio/eng.ogg", enabled: true },
  "/l/": { audioFile: "/phonics-audio/l.ogg", enabled: true },
  "/r/": { audioFile: "/phonics-audio/r.ogg", enabled: true },
  "/j/": { audioFile: "/phonics-audio/j.ogg", enabled: true },
  "/w/": { audioFile: "/phonics-audio/w.ogg", enabled: true },
  "/tʃ/": { audioFile: "/phonics-audio/tsh.ogg", enabled: true },
  "/dʒ/": { audioFile: "/phonics-audio/dzh.ogg", enabled: true },
};
